package transition

import (
	"context"
	"fmt"
	"net"
	"reflect"
	"strconv"
	"strings"

	"github.com/istio-ecosystem/mesh-operator/pkg/features"

	"github.com/istio-ecosystem/mesh-operator/pkg/constants"

	commonmetrics "github.com/istio-ecosystem/mesh-operator/pkg/common/metrics"

	"k8s.io/apimachinery/pkg/runtime/schema"

	"github.com/istio-ecosystem/mesh-operator/pkg/templating"

	k8serrors "k8s.io/apimachinery/pkg/api/errors"

	"github.com/istio-ecosystem/mesh-operator/pkg/common"
	"github.com/istio-ecosystem/mesh-operator/pkg/kube"
	"github.com/prometheus/client_golang/prometheus"
	"go.uber.org/zap"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// MeshConfigComparer compares the config generated by copilot with that generated by mesh-operator.
// See upstream docs for more details.
type MeshConfigComparer interface {
	// DiffWithCopilotConfig - compare the config provided to the copilot generated config in cluster
	// Internally, perform logging and metrics collection.
	// Returns templating.GeneratedConfig comprising objects that match copilot config
	// and can be applied to cluster by mesh operator.
	DiffWithCopilotConfig(config *templating.GeneratedConfig, object *unstructured.Unstructured,
		metadata map[string]string) (*templating.GeneratedConfig, error)

	DiffAdditionalTemplates(config templating.GeneratedConfig, object *unstructured.Unstructured) *templating.GeneratedConfig
}

type meshConfigComparer struct {
	logger          *zap.SugaredLogger
	primaryClient   kube.Client
	metricsRegistry *prometheus.Registry
	clusterName     string
}

func NewMeshConfigComparer(
	logger *zap.SugaredLogger,
	primaryClient kube.Client,
	metricsRegistry *prometheus.Registry,
	clusterName string) MeshConfigComparer {
	return &meshConfigComparer{
		logger:          logger,
		primaryClient:   primaryClient,
		metricsRegistry: metricsRegistry,
		clusterName:     clusterName,
	}
}

func (c *meshConfigComparer) DiffWithCopilotConfig(generatedConfig *templating.GeneratedConfig,
	object *unstructured.Unstructured, metadata map[string]string) (
	*templating.GeneratedConfig, error) {

	if object == nil {
		c.logger.Warnf("no object provided, not running comparison. Returning mop-generated config.")
		return generatedConfig, nil
	}

	ctxLogger := c.logger.With(
		"namespace", object.GetNamespace(),
		"objectName", object.GetName(),
		"kind", object.GetKind(),
		"template", generatedConfig.TemplateType)

	if !MopTransitionAllowCopilotRendering {
		ctxLogger.Debug("comparison with copilot config is not allowed. Returning mop-generated config.")
		return generatedConfig, nil
	}

	// If the template is deprecated by copilot, apply MOP-generated config.
	if isTemplateDeprecatedByCopilot(generatedConfig.TemplateType) {
		c.handleDeprecatedCopilotTemplates(object, generatedConfig.TemplateType, ctxLogger)
		return generatedConfig, nil
	}

	copilotGeneratedObjects, err := c.getCopilotGeneratedObjects(generatedConfig, object, metadata)
	if err != nil {
		return nil, fmt.Errorf("got an error while retrieving copilot generated objects: %s", err)
	}

	c.raiseTransitionGauge(MeshConfigTotal, object, generatedConfig.TemplateType)
	copilotIndex := c.indexResources(copilotGeneratedObjects)

	//0. If copilotGeneratedObject not found in the cluster, apply MOP generated config
	if len(copilotIndex) == 0 {
		ctxLogger.Info("mop-transition: copilotGeneratedObject not found, apply mop-generated config")
		c.incrementMetric(MopTransitionSuccess, object, generatedConfig.TemplateType)
		c.eraseTransitionGauge(MeshConfigTransitionErrors, object, generatedConfig.TemplateType)
		return generatedConfig, nil
	}

	// exclude config generated by additional template types
	additionalObjects := excludeAdditionalTemplateConfig(generatedConfig)
	mopIndex := c.indexResources(generatedConfig.FlattenConfig())

	// 1. Compare the number of objects generated
	c.handleSizeComparisons(copilotIndex, mopIndex, object, generatedConfig.TemplateType, ctxLogger)

	// 2. Compare the actual object collections, return the matching objects
	matchingObjects := c.compareCollections(copilotIndex, mopIndex, object, generatedConfig.TemplateType, ctxLogger)

	finalConfig := templating.UnflattenConfig(matchingObjects, generatedConfig.TemplateType)

	// add additionalObjects back to the final config
	includeAdditionalTemplateConfig(finalConfig, additionalObjects)

	return finalConfig, nil
}

func (c *meshConfigComparer) DiffAdditionalTemplates(config templating.GeneratedConfig, object *unstructured.Unstructured) *templating.GeneratedConfig {
	externalName, hasExternalName, _ := unstructured.NestedString(object.Object, "spec", "externalName")
	svcType, hasType, _ := unstructured.NestedString(object.Object, "spec", "type")

	if hasType && svcType == "LoadBalancer" || hasExternalName && net.ParseIP(externalName) != nil {
		// No additional templates expected for the service
		return &config
	}

	addonTemplateName := config.TemplateType + "_addon"
	mopAddonObjects := config.Config[addonTemplateName]

	// For debug purposes. Collect the generated template names
	generateConfigTemplates := ""
	for k := range config.Config {
		generateConfigTemplates += k + " "
	}

	for _, templateType := range additionalTemplateTypes {

		ctxLogger := c.logger.With(
			"namespace", object.GetNamespace(),
			"objectName", object.GetName(),
			"kind", object.GetKind(),
			"templateType", templateType,
			"baseTemplateType", config.TemplateType)

		if isTemplateDeprecatedByCopilot(templateType) {
			continue
		}

		switch templateType {
		case ProtocolFilters:
			if shouldHaveProtocolFilter(object) {
				thriftFilterName := getResourceNameFromMetadata(object, ThriftFilterSuffix)
				_, mopFilter := findConfigObjectByName(mopAddonObjects, thriftFilterName)
				if mopFilter == nil {
					ctxLogger.Info("mop-transition: mop didn't generate thrift filter")
					c.incrementMetric(MopTransitionMissingConfigs, object, templateType)
					c.raiseTransitionGauge(MeshConfigTransitionErrors, object, templateType)
					continue
				}

				copilotFilter, err := c.findDynamicResourceByName(constants.EnvoyFilterResource, object.GetNamespace(), thriftFilterName)
				if err != nil {
					ctxLogger.Errorf("mop-transition: failed to get copilot thrift-filter %w", err)
					copilotFilter = nil
				}

				ctxLogger.Debugf("mop-transition-addon. Templates: %s mopFilter: %t copilotFilter:%t", generateConfigTemplates, mopFilter != nil, copilotFilter != nil)

				var mopIndex, copilotIndex map[string]*unstructured.Unstructured
				if mopFilter != nil {
					mopIndex = c.indexResources([]*unstructured.Unstructured{mopFilter})
				}
				if copilotFilter != nil {
					copilotIndex = c.indexResources([]*unstructured.Unstructured{copilotFilter})
				}

				mopAddonObjects = c.compareAddonObjects(ctxLogger, copilotIndex, mopIndex, object, mopAddonObjects, templateType)
			}
		case GenericServiceFilters, HawkingServiceFilters:
			if ok, serviceFilterList, err := shouldHaveAdditionalServiceTemplates(object, templateType); err != nil {
				ctxLogger.Errorf("mop-transition: comparison failed for additional template %s, error: %v", templateType, err)
				c.incrementMetric(MopTransitionComparisonFailure, object, templateType)
			} else if ok {
				mopGeneratedServiceFilters := c.extractMopGeneratedServiceFilters(object, templateType, mopAddonObjects, serviceFilterList)
				mopIndex := c.indexResources(mopGeneratedServiceFilters)

				copilotGeneratedServiceFilters := c.fetchAdditionalServiceFiltersGeneratedByCopilot(object, templateType, serviceFilterList, ctxLogger)
				copilotIndex := c.indexResources(copilotGeneratedServiceFilters)

				mopAddonObjects = c.compareAddonObjects(ctxLogger, copilotIndex, mopIndex, object, mopAddonObjects, templateType)
			}
		case RateLimitingServiceFilters:
			if features.FDType == UnifiedEngagementFd && !common.SliceContains(RlsExcludedNamespaces, object.GetNamespace()) {
				_, hasCell := object.GetLabels()["p_cell"]
				if hasCell {
					rlsFilterName := getResourceNameFromMetadata(object, RatelimitFilterSuffix)
					_, mopFilter := findConfigObjectByName(mopAddonObjects, rlsFilterName)
					if mopFilter == nil {
						ctxLogger.Info("mop-transition: mop didn't generate rate-limiting-service filter")
						c.incrementMetric(MopTransitionMissingConfigs, object, templateType)
						c.raiseTransitionGauge(MeshConfigTransitionErrors, object, templateType)
						continue
					}

					copilotFilter, err := c.findDynamicResourceByName(constants.EnvoyFilterResource, object.GetNamespace(), rlsFilterName)
					if err != nil {
						ctxLogger.Errorf("mop-transition: failed to get copilot rls-filter %w", err)
						copilotFilter = nil
					}

					ctxLogger.Debugf("mop-transition-addon. Templates: %s mopFilter: %t copilotFilter:%t", generateConfigTemplates, mopFilter != nil, copilotFilter != nil)

					var mopIndex, copilotIndex map[string]*unstructured.Unstructured
					if mopFilter != nil {
						mopIndex = c.indexResources([]*unstructured.Unstructured{mopFilter})
					}
					if copilotFilter != nil {
						copilotIndex = c.indexResources([]*unstructured.Unstructured{copilotFilter})
					}
					mopAddonObjects = c.compareAddonObjects(ctxLogger, copilotIndex, mopIndex, object, mopAddonObjects, templateType)
				}
			}
		}
	}

	if len(mopAddonObjects) > 0 {
		config.Config[addonTemplateName] = mopAddonObjects
	} else {
		delete(config.Config, addonTemplateName)
	}
	return &config
}

func (c *meshConfigComparer) compareAddonObjects(ctxLogger *zap.SugaredLogger, copilotIndex, mopIndex map[string]*unstructured.Unstructured, object *unstructured.Unstructured, mopAddonObjects []*unstructured.Unstructured, templateType string) []*unstructured.Unstructured {
	// Compare the number of objects generated
	c.handleSizeComparisons(copilotIndex, mopIndex, object, templateType, ctxLogger)

	// Compare the actual object collections, return the matching objects
	matchingObjects := c.compareCollections(copilotIndex, mopIndex, object, templateType, ctxLogger)
	matchingObjectIndex := c.indexResources(matchingObjects)

	// remove non matching objects from add on list
	if len(matchingObjects) != len(mopIndex) {
		var finalAddOnList []*unstructured.Unstructured
		nonMatchingResources := getNonMatchingObjects(matchingObjectIndex, mopIndex)
		for _, obj := range mopAddonObjects {
			if common.SliceContains(nonMatchingResources, obj.GetName()) {
				continue
			}
			finalAddOnList = append(finalAddOnList, obj)
		}
		mopAddonObjects = finalAddOnList
	}
	return mopAddonObjects
}

func (c *meshConfigComparer) recordAddonTransitionFailure(object *unstructured.Unstructured, transitionMetric TransitionMetrics, templateType string) {
	c.incrementMetric(transitionMetric, object, templateType)
	c.raiseTransitionGauge(MeshConfigTransitionErrors, object, templateType)
}

func (c *meshConfigComparer) handleDeprecatedCopilotTemplates(object *unstructured.Unstructured, templateType string,
	ctxLogger *zap.SugaredLogger) {
	ctxLogger.Info("mop-transition: deprecated copilot config.")
	c.incrementMetric(MopTransitionDeprecatedCopilotTemplate, object, templateType)
	c.incrementMetric(MopTransitionSuccess, object, templateType)
	c.eraseTransitionGauge(MeshConfigTransitionErrors, object, templateType)
}

func (c *meshConfigComparer) handleSizeComparisons(copilotIndex map[string]*unstructured.Unstructured,
	mopIndex map[string]*unstructured.Unstructured,
	object *unstructured.Unstructured,
	templateType string,
	ctxLogger *zap.SugaredLogger) {

	if len(copilotIndex) > len(mopIndex) {
		ctxLogger.Infof("mop-transition: mop is missing resources. Copilot:[%s]. MeshOp:[%s]",
			getLoggableKeys(copilotIndex), getLoggableKeys(mopIndex))
		c.incrementMetric(MopTransitionMissingConfigs, object, templateType)
		c.raiseTransitionGauge(MeshConfigTransitionErrors, object, templateType)
	}

	if len(copilotIndex) < len(mopIndex) {
		c.incrementMetric(MopTransitionExtraConfigs, object, templateType)
		c.raiseTransitionGauge(MeshConfigTransitionErrors, object, templateType)
		ctxLogger.Infof("mop-transition: mop generated more resources. Copilot:[%s]. MeshOp:[%s]",
			getLoggableKeys(copilotIndex), getLoggableKeys(mopIndex))
	}
}

func (c *meshConfigComparer) compareCollections(copilotIndex map[string]*unstructured.Unstructured,
	mopIndex map[string]*unstructured.Unstructured,
	object *unstructured.Unstructured,
	templateType string,
	ctxLogger *zap.SugaredLogger) []*unstructured.Unstructured {

	ctxLogger.Infof("mop-transition: starting config comparison. Copilot:[%s]. MeshOp:[%s]",
		getLoggableKeys(copilotIndex), getLoggableKeys(mopIndex))

	var matchingObjects []*unstructured.Unstructured
	for objectKey, mopObject := range mopIndex {
		if copilotObject, ok := copilotIndex[objectKey]; ok {
			if c.compare(mopObject, copilotObject, ctxLogger) {
				modifyOwners(copilotObject.GetOwnerReferences(), mopObject)
				propagateMeshLabels(mopObject, copilotObject)
				matchingObjects = append(matchingObjects, mopObject)
			} else {
				c.incrementMetric(MopTransitionDifferentConfigSpec, object, templateType)
				c.raiseTransitionGauge(MeshConfigTransitionErrors, object, templateType)
			}
		} else {
			ctxLogger.Infof("mop-transition: MOP generated a resource that copilot did not: %s", objectKey)
			c.incrementMetric(MopTransitionUnknownConfigGenerated, object, templateType)
			c.raiseTransitionGauge(MeshConfigTransitionErrors, object, templateType)
		}
	}
	if len(mopIndex) == len(copilotIndex) && len(matchingObjects) == len(mopIndex) {
		ctxLogger.Infof("mop-transition: all MOP generated objects are same as that of copilot (objects count: %d)", len(mopIndex))
		c.incrementMetric(MopTransitionSuccess, object, templateType)
		c.eraseTransitionGauge(MeshConfigTransitionErrors, object, templateType)
	}

	return matchingObjects
}

func (c *meshConfigComparer) compare(generatedByMop *unstructured.Unstructured, generatedByCopilot *unstructured.
	Unstructured, ctxLogger *zap.SugaredLogger) bool {
	key := getKey(generatedByMop)

	if compareLabels(generatedByMop, generatedByCopilot, ctxLogger) {
		removeArgoUpdatedSubsetLabel(generatedByCopilot) // Only from the config fetched from the cluster.

		if !reflect.DeepEqual(generatedByMop.Object["spec"], generatedByCopilot.Object["spec"]) {
			ctxLogger.Infof("mop-transition: MOP generated a different spec for resource: %s."+
				" Copilot: %s, MOP: %s", key, generatedByCopilot.Object["spec"], generatedByMop.Object["spec"])
			return false
		}
		ctxLogger.Infof("mop-transition: MOP generated a resource same as copilot: %s", key)
		return true
	}
	return false
}

func compareLabels(generatedByMop *unstructured.Unstructured, generatedByCopilot *unstructured.Unstructured,
	logger *zap.SugaredLogger) bool {
	copilotLabels := generatedByCopilot.GetLabels()
	mopLabels := generatedByMop.GetLabels()

	for _, label := range []string{VersionLabel, TypeLabel} {
		copilotVal := copilotLabels[label]
		mopVal := mopLabels[label]
		if copilotVal != mopVal {
			logger.Infof("mop-transition: label %s was different for object %s. "+
				"Value for copilot was %s, and for mop was %s", label, getKey(generatedByMop), copilotVal, mopVal)
			return false
		}
	}
	return true
}

func modifyOwners(existingOwners []metav1.OwnerReference, mopObject *unstructured.Unstructured) {
	if len(existingOwners) == 0 {
		return
	}

	existingOwners = common.MergeOwnerReferences(existingOwners, mopObject.GetOwnerReferences())

	mopObject.SetOwnerReferences(existingOwners)
}

func propagateMeshLabels(generatedByMop, generatedByCopilot *unstructured.Unstructured) {
	newLabels := generatedByMop.GetLabels()
	if newLabels == nil {
		newLabels = map[string]string{}
	}

	for k, v := range generatedByCopilot.GetLabels() {
		if strings.HasPrefix(k, "mesh.io.example.com") ||
			strings.HasPrefix(k, "routing.mesh.io.example.com") {
			newLabels[k] = v
		}
	}
	if len(newLabels) > 0 {
		generatedByMop.SetLabels(newLabels)
	}
}

// getCopilotGeneratedObjects gets the virtual services and destination rules generated by copilot for the given object.
// The resources are selected based on:
// main vs and dr - by the service name
// delegate vs (if any) - are retrieved by parsing out the delegate names from the main vs record
func (c *meshConfigComparer) getCopilotGeneratedObjects(config *templating.GeneratedConfig,
	object *unstructured.Unstructured, metadata map[string]string) ([]*unstructured.Unstructured, error) {

	var result = []*unstructured.Unstructured{}

	// Get main VS and its delegates
	mainVs, err := c.primaryClient.Dynamic().
		Resource(constants.VirtualServiceResource).
		Namespace(object.GetNamespace()).
		Get(context.TODO(), object.GetName(), metav1.GetOptions{})
	if err != nil {
		if !k8serrors.IsNotFound(err) {
			return nil, fmt.Errorf("failed to obain main VS, %w", err)
		}
	} else {
		_, exists := mainVs.GetLabels()["mesh.io.example.com/managed-by"]
		if exists {
			result = append(result, mainVs)
			delegates, err := c.getDelegates(mainVs)
			if err != nil {
				return nil, fmt.Errorf("failed to obain delegates, %w", err)
			}

			result = append(result, delegates...)
		}
	}

	if config.TemplateType == DefaultExternalService {
		preProcessExtSvcVs(result)
	}

	// Get DR
	dr, err := c.primaryClient.Dynamic().
		Resource(constants.DestinationRuleResource).
		Namespace(object.GetNamespace()).
		Get(context.TODO(), object.GetName(), metav1.GetOptions{})
	if err != nil {
		if !k8serrors.IsNotFound(err) {
			return nil, fmt.Errorf("failed to obain DR, %w", err)
		}
	} else {
		_, exists := dr.GetLabels()["mesh.io.example.com/managed-by"]
		if exists {
			result = append(result, dr)
		}
	}

	additionalConfig, err := c.fetchAdditionalConfigForTemplateType(config.TemplateType, object, metadata)
	if err != nil {
		return nil, fmt.Errorf("failed to obtain additional config for templateType %s, error: %w", config.TemplateType, err)
	}
	result = append(result, additionalConfig...)

	return result, nil
}

// fetchAdditionalConfigForTemplateType fetches additional copilot generated config for a given templateType
func (c *meshConfigComparer) fetchAdditionalConfigForTemplateType(templateType string, object *unstructured.
	Unstructured, metadata map[string]string) ([]*unstructured.Unstructured, error) {
	result := make([]*unstructured.Unstructured, 0)

	switch templateType {

	// This is a special case of STS. Iterate over replica sets and fetch VS/DR/SE for each, if exists
	case DefaultStatefulSet, EmailinfraEaas, SolrService, Vagabond:
		if replicaSets, replicaSetsExists := metadata[constants.ContextStsReplicas]; replicaSetsExists {
			replicas, err := strconv.Atoi(replicaSets)
			replicasetName := metadata[constants.ContextStsReplicaName]
			if err == nil {
				for i := 0; i < replicas; i++ {
					objName := fmt.Sprintf("%s-%d", replicasetName, i)
					gvrList := []schema.GroupVersionResource{
						constants.DestinationRuleResource,
						constants.VirtualServiceResource,
						constants.ServiceEntryResource}
					for _, gvr := range gvrList {
						configObject, err := c.findDynamicResourceByName(gvr, object.GetNamespace(), objName)
						if err != nil {
							return nil, err
						}
						if configObject != nil {
							result = append(result, configObject)
						}
					}
				}
			} else {
				return nil, err
			}
		}

	default:
		// handles scenario for templateTypes defined inside configListByTemplateType map
		if configList, ok := configListByTemplateType[templateType]; ok {
			for _, configInfo := range configList {
				configName, configNamespace, err := configInfo.getConfigObjectNameAndNamespace(object)
				if err != nil {
					c.logger.Error("error while fetching additional copilot config", err)
					return nil, err
				}
				configObject, err := c.findDynamicResourceByName(configInfo.gvr, configNamespace, configName)
				if err != nil {
					return nil, err
				}
				if configObject != nil {
					result = append(result, configObject)
				}
			}
		}
	}

	return result, nil
}

func (c *meshConfigComparer) findDynamicResourceByName(resource schema.GroupVersionResource, namespace, name string,
) (*unstructured.Unstructured, error) {
	objInCluster, err := c.primaryClient.Dynamic().Resource(resource).
		Namespace(namespace).
		Get(context.TODO(), name, metav1.GetOptions{})

	if err == nil {
		_, exists := objInCluster.GetLabels()["mesh.io.example.com/managed-by"]
		if exists {
			return objInCluster, nil
		}
	}

	if k8serrors.IsNotFound(err) {
		return nil, nil
	}
	return nil, err
}

func (c *meshConfigComparer) getDelegates(vs *unstructured.Unstructured) ([]*unstructured.Unstructured, error) {
	routes, found, err := unstructured.NestedSlice(vs.Object, "spec", "http")

	if err != nil || !found {
		return []*unstructured.Unstructured{}, nil
	}

	delegates := make([]*unstructured.Unstructured, 0)
	for _, route := range routes {
		delegateName, found, err := unstructured.NestedString(route.(map[string]interface{}), "delegate", "name")

		if err != nil || !found {
			continue
		}

		delegateVs, err := c.primaryClient.Dynamic().Resource(constants.VirtualServiceResource).
			Namespace(vs.GetNamespace()).
			Get(context.TODO(), delegateName, metav1.GetOptions{})

		if err != nil {
			if !k8serrors.IsNotFound(err) {
				return nil, err
			}
			continue
		}

		_, exists := delegateVs.GetLabels()["mesh.io.example.com/managed-by"]
		if exists {
			delegates = append(delegates, delegateVs)
		}
	}

	return delegates, nil
}

func (c *meshConfigComparer) indexResources(config []*unstructured.Unstructured) map[string]*unstructured.Unstructured {
	result := map[string]*unstructured.Unstructured{}
	for _, obj := range config {
		key := getKey(obj)
		result[key] = obj
	}
	return result
}

func (c *meshConfigComparer) fetchAdditionalServiceFiltersGeneratedByCopilot(service *unstructured.Unstructured, templateType string, serviceFilterList []string, ctxLogger *zap.SugaredLogger) []*unstructured.Unstructured {
	var additionalServiceFilters = []*unstructured.Unstructured{}
	for _, serviceFilter := range serviceFilterList {
		if common.SliceContains(allowedServiceFiltersForTemplateType[templateType], serviceFilter) {
			// fetch the filter from cluster
			serviceFilterInfo := additionalServiceFilterInfo[templateType+"_"+serviceFilter]
			configObject, err := c.findDynamicResourceByName(serviceFilterInfo.gvr, service.GetNamespace(), serviceFilterInfo.getName(service))
			if err != nil {
				ctxLogger.Errorf("mop-transition: failed to get copilot additional service filter, error %w", err)
				c.incrementMetric(MopTransitionFetchCopilotResourceFailure, service, templateType)
				c.raiseTransitionGauge(MeshConfigTransitionErrors, service, templateType)
				continue
			}
			if configObject != nil {
				if serviceFilter == "sql-server" {
					value := common.GetAnnotationOrAlias(constants.RoutingConfigEnabledAnnotation, configObject.GetAnnotations())
					if value == "false" {
						additionalServiceFilters = append(additionalServiceFilters, configObject)
					}
				} else {
					additionalServiceFilters = append(additionalServiceFilters, configObject)
				}
			}
		}
	}
	return additionalServiceFilters
}

func (c *meshConfigComparer) extractMopGeneratedServiceFilters(service *unstructured.Unstructured, templateType string, config []*unstructured.Unstructured, serviceFilterList []string) []*unstructured.Unstructured {
	var mopGeneratedServiceFilters = []*unstructured.Unstructured{}
	mopIndex := c.indexResources(config)
	for _, serviceFilter := range serviceFilterList {
		if common.SliceContains(allowedServiceFiltersForTemplateType[templateType], serviceFilter) {
			serviceFilterInfo := additionalServiceFilterInfo[templateType+"_"+serviceFilter]
			key := serviceFilterInfo.gvr.GroupVersion().String() + "/" + serviceFilterInfo.kind + "/" + service.GetNamespace() + "/" + serviceFilterInfo.getName(service)
			if object, ok := mopIndex[key]; ok {
				mopGeneratedServiceFilters = append(mopGeneratedServiceFilters, object)
			}
		}
	}
	return mopGeneratedServiceFilters
}

func (c *meshConfigComparer) raiseTransitionGauge(metric TransitionMetrics, object *unstructured.Unstructured,
	template string) {
	lbls := commonmetrics.GetLabelsForReconciledResource(object.GetKind(), c.clusterName, object.GetNamespace(), object.GetName(), object.GetName(), object.GetKind(), template)
	commonmetrics.GetOrRegisterGaugeWithLabels(metric.GetName(), lbls, c.metricsRegistry).Set(1)
}

func (c *meshConfigComparer) eraseTransitionGauge(metric TransitionMetrics, object *unstructured.Unstructured,
	template string) {
	lbls := commonmetrics.GetLabelsForReconciledResource(object.GetKind(), c.clusterName, object.GetNamespace(), object.GetName(), object.GetName(), object.GetKind(), template)
	commonmetrics.UnregisterGaugeWithLabels(metric.GetName(), lbls, c.metricsRegistry)
}

func (c *meshConfigComparer) incrementMetric(metric TransitionMetrics, object *unstructured.Unstructured, templateType string) {
	lbls := commonmetrics.GetLabelsForReconciledResource(object.GetKind(), c.clusterName, object.GetNamespace(), object.GetName(), object.GetName(), object.GetKind(), templateType)
	commonmetrics.GetOrRegisterCounterWithLabels(metric.GetName(), lbls, c.metricsRegistry).Inc()
}

func EraseTransitionStats(registry *prometheus.Registry, namespace string, kind string, svcName string) {
	commonmetrics.EraseMetricsForK8sResource(
		registry,
		[]string{
			MeshConfigTotal.GetName(),
			MeshConfigTransitionErrors.GetName(),
			MopTransitionDeprecatedCopilotTemplate.GetName(),
			MopTransitionSuccess.GetName(),
		},
		map[string]string{
			commonmetrics.NamespaceLabel:    namespace,
			commonmetrics.ResourceNameLabel: svcName,
			commonmetrics.ResourceKind:      kind,
		})
}

func getNonMatchingObjects(matchingObjectsIndex map[string]*unstructured.Unstructured, mopServiceFilterIndex map[string]*unstructured.Unstructured) []string {
	var nonMatchingObjectList []string
	for index, obj := range mopServiceFilterIndex {
		if _, ok := matchingObjectsIndex[index]; !ok {
			nonMatchingObjectList = append(nonMatchingObjectList, obj.GetName())
		}
	}
	return nonMatchingObjectList
}

func excludeAdditionalTemplateConfig(config *templating.GeneratedConfig) []*unstructured.Unstructured {
	addOnTemplateName := config.TemplateType + "_addon"
	mopAddonObjects := config.Config[addOnTemplateName]
	delete(config.Config, addOnTemplateName)
	return mopAddonObjects
}

func includeAdditionalTemplateConfig(config *templating.GeneratedConfig, additionalTemplateConfig []*unstructured.Unstructured) {
	if additionalTemplateConfig == nil {
		return
	}
	addOnTemplateName := config.TemplateType + "_addon"
	config.Config[addOnTemplateName] = additionalTemplateConfig
}
