//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessLogConfig) DeepCopyInto(out *AccessLogConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessLogConfig.
func (in *AccessLogConfig) DeepCopy() *AccessLogConfig {
	if in == nil {
		return nil
	}
	out := new(AccessLogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Action) DeepCopyInto(out *Action) {
	*out = *in
	if in.RequestHeaders != nil {
		in, out := &in.RequestHeaders, &out.RequestHeaders
		*out = new(RequestHeaders)
		**out = **in
	}
	if in.GenericKey != nil {
		in, out := &in.GenericKey, &out.GenericKey
		*out = new(GenericKey)
		**out = **in
	}
	if in.HeaderValueMatch != nil {
		in, out := &in.HeaderValueMatch, &out.HeaderValueMatch
		*out = new(HeaderValueMatch)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Action.
func (in *Action) DeepCopy() *Action {
	if in == nil {
		return nil
	}
	out := new(Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRule) DeepCopyInto(out *ActionRule) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]Action, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRule.
func (in *ActionRule) DeepCopy() *ActionRule {
	if in == nil {
		return nil
	}
	out := new(ActionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveHealthCheck) DeepCopyInto(out *ActiveHealthCheck) {
	*out = *in
	if in.PortLevelHealthChecks != nil {
		in, out := &in.PortLevelHealthChecks, &out.PortLevelHealthChecks
		*out = make([]PortLevelHealthCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActivateExtensionLabels != nil {
		in, out := &in.ActivateExtensionLabels, &out.ActivateExtensionLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveHealthCheck.
func (in *ActiveHealthCheck) DeepCopy() *ActiveHealthCheck {
	if in == nil {
		return nil
	}
	out := new(ActiveHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Attribute) DeepCopyInto(out *Attribute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Attribute.
func (in *Attribute) DeepCopy() *Attribute {
	if in == nil {
		return nil
	}
	out := new(Attribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorityFilter) DeepCopyInto(out *AuthorityFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorityFilter.
func (in *AuthorityFilter) DeepCopy() *AuthorityFilter {
	if in == nil {
		return nil
	}
	out := new(AuthorityFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseRateLimitConfig) DeepCopyInto(out *BaseRateLimitConfig) {
	*out = *in
	if in.InboundPorts != nil {
		in, out := &in.InboundPorts, &out.InboundPorts
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.ActionRules != nil {
		in, out := &in.ActionRules, &out.ActionRules
		*out = make([]ActionRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseRateLimitConfig.
func (in *BaseRateLimitConfig) DeepCopy() *BaseRateLimitConfig {
	if in == nil {
		return nil
	}
	out := new(BaseRateLimitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueGreenStrategy) DeepCopyInto(out *BlueGreenStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueGreenStrategy.
func (in *BlueGreenStrategy) DeepCopy() *BlueGreenStrategy {
	if in == nil {
		return nil
	}
	out := new(BlueGreenStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConfigClientSide) DeepCopyInto(out *ClusterConfigClientSide) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConfigClientSide.
func (in *ClusterConfigClientSide) DeepCopy() *ClusterConfigClientSide {
	if in == nil {
		return nil
	}
	out := new(ClusterConfigClientSide)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConfigServerSide) DeepCopyInto(out *ClusterConfigServerSide) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConfigServerSide.
func (in *ClusterConfigServerSide) DeepCopy() *ClusterConfigServerSide {
	if in == nil {
		return nil
	}
	out := new(ClusterConfigServerSide)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTrafficPolicy) DeepCopyInto(out *ClusterTrafficPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTrafficPolicy.
func (in *ClusterTrafficPolicy) DeepCopy() *ClusterTrafficPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterTrafficPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTrafficPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTrafficPolicyList) DeepCopyInto(out *ClusterTrafficPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterTrafficPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTrafficPolicyList.
func (in *ClusterTrafficPolicyList) DeepCopy() *ClusterTrafficPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterTrafficPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTrafficPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTrafficPolicySpec) DeepCopyInto(out *ClusterTrafficPolicySpec) {
	*out = *in
	in.ClusterTrafficStrategy.DeepCopyInto(&out.ClusterTrafficStrategy)
	if in.ConfigContext != nil {
		in, out := &in.ConfigContext, &out.ConfigContext
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTrafficPolicySpec.
func (in *ClusterTrafficPolicySpec) DeepCopy() *ClusterTrafficPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterTrafficPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTrafficPolicyStatus) DeepCopyInto(out *ClusterTrafficPolicyStatus) {
	*out = *in
	if in.LastReconciledTime != nil {
		in, out := &in.LastReconciledTime, &out.LastReconciledTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTrafficPolicyStatus.
func (in *ClusterTrafficPolicyStatus) DeepCopy() *ClusterTrafficPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterTrafficPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTrafficStrategy) DeepCopyInto(out *ClusterTrafficStrategy) {
	*out = *in
	out.BlueGreen = in.BlueGreen
	in.GlobalCanary.DeepCopyInto(&out.GlobalCanary)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTrafficStrategy.
func (in *ClusterTrafficStrategy) DeepCopy() *ClusterTrafficStrategy {
	if in == nil {
		return nil
	}
	out := new(ClusterTrafficStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cookie) DeepCopyInto(out *Cookie) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make([]Attribute, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cookie.
func (in *Cookie) DeepCopy() *Cookie {
	if in == nil {
		return nil
	}
	out := new(Cookie)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredEgressHosts) DeepCopyInto(out *DiscoveredEgressHosts) {
	*out = *in
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = make([]Host, len(*in))
		copy(*out, *in)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]Host, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredEgressHosts.
func (in *DiscoveredEgressHosts) DeepCopy() *DiscoveredEgressHosts {
	if in == nil {
		return nil
	}
	out := new(DiscoveredEgressHosts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressHosts) DeepCopyInto(out *EgressHosts) {
	*out = *in
	if in.Discovered != nil {
		in, out := &in.Discovered, &out.Discovered
		*out = new(DiscoveredEgressHosts)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressHosts.
func (in *EgressHosts) DeepCopy() *EgressHosts {
	if in == nil {
		return nil
	}
	out := new(EgressHosts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionElement) DeepCopyInto(out *ExtensionElement) {
	*out = *in
	if in.FaultFilter != nil {
		in, out := &in.FaultFilter, &out.FaultFilter
		*out = new(HttpFaultFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.PayloadStats != nil {
		in, out := &in.PayloadStats, &out.PayloadStats
		*out = new(StatsFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.GatewayFilter != nil {
		in, out := &in.GatewayFilter, &out.GatewayFilter
		*out = new(GatewayProxyFilter)
		**out = **in
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxOutboundFrames != nil {
		in, out := &in.MaxOutboundFrames, &out.MaxOutboundFrames
		*out = new(MaxOutboundFrames)
		**out = **in
	}
	if in.ServerMaxOutboundFrames != nil {
		in, out := &in.ServerMaxOutboundFrames, &out.ServerMaxOutboundFrames
		*out = new(ServerMaxOutboundFrames)
		**out = **in
	}
	if in.LocalRateLimitFilter != nil {
		in, out := &in.LocalRateLimitFilter, &out.LocalRateLimitFilter
		*out = new(LocalRateLimitFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.GRPCJsonTranscoderFilter != nil {
		in, out := &in.GRPCJsonTranscoderFilter, &out.GRPCJsonTranscoderFilter
		*out = new(GRPCJsonTranscoderFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.ActiveHealthCheckFilter != nil {
		in, out := &in.ActiveHealthCheckFilter, &out.ActiveHealthCheckFilter
		*out = new(ActiveHealthCheck)
		(*in).DeepCopyInto(*out)
	}
	if in.Authority != nil {
		in, out := &in.Authority, &out.Authority
		*out = new(AuthorityFilter)
		**out = **in
	}
	if in.GzipFilter != nil {
		in, out := &in.GzipFilter, &out.GzipFilter
		*out = new(GzipFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.OAuth2Filter != nil {
		in, out := &in.OAuth2Filter, &out.OAuth2Filter
		*out = new(OAuth2Filter)
		(*in).DeepCopyInto(*out)
	}
	if in.MixedMode != nil {
		in, out := &in.MixedMode, &out.MixedMode
		*out = new(MixedMode)
		(*in).DeepCopyInto(*out)
	}
	if in.HealthCheckFilter != nil {
		in, out := &in.HealthCheckFilter, &out.HealthCheckFilter
		*out = new(HealthCheckFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancerConfig != nil {
		in, out := &in.LoadBalancerConfig, &out.LoadBalancerConfig
		*out = new(LoadBalancerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GlobalRateLimitFilter != nil {
		in, out := &in.GlobalRateLimitFilter, &out.GlobalRateLimitFilter
		*out = new(GlobalRateLimitFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.IngressGlobalRateLimitFilter != nil {
		in, out := &in.IngressGlobalRateLimitFilter, &out.IngressGlobalRateLimitFilter
		*out = new(IngressRateLimitFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.IngressRequestHeaders != nil {
		in, out := &in.IngressRequestHeaders, &out.IngressRequestHeaders
		*out = new(IngressRequestHeaders)
		(*in).DeepCopyInto(*out)
	}
	if in.IngressResponseHeaders != nil {
		in, out := &in.IngressResponseHeaders, &out.IngressResponseHeaders
		*out = new(IngressResponseHeaders)
		(*in).DeepCopyInto(*out)
	}
	if in.IngressCookieAttributes != nil {
		in, out := &in.IngressCookieAttributes, &out.IngressCookieAttributes
		*out = new(IngressCookieAttribute)
		(*in).DeepCopyInto(*out)
	}
	if in.IngressLua != nil {
		in, out := &in.IngressLua, &out.IngressLua
		*out = new(IngressLua)
		(*in).DeepCopyInto(*out)
	}
	if in.MeshRequestHeaders != nil {
		in, out := &in.MeshRequestHeaders, &out.MeshRequestHeaders
		*out = new(MeshRequestHeaders)
		(*in).DeepCopyInto(*out)
	}
	if in.MeshRequestHeadersPerRoute != nil {
		in, out := &in.MeshRequestHeadersPerRoute, &out.MeshRequestHeadersPerRoute
		*out = new(MeshRequestHeadersPerRoute)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterConfigServerSide != nil {
		in, out := &in.ClusterConfigServerSide, &out.ClusterConfigServerSide
		*out = new(ClusterConfigServerSide)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterConfigClientSide != nil {
		in, out := &in.ClusterConfigClientSide, &out.ClusterConfigClientSide
		*out = new(ClusterConfigClientSide)
		(*in).DeepCopyInto(*out)
	}
	if in.SparkConfiguration != nil {
		in, out := &in.SparkConfiguration, &out.SparkConfiguration
		*out = new(SparkConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ProxyProtocolFilter != nil {
		in, out := &in.ProxyProtocolFilter, &out.ProxyProtocolFilter
		*out = new(ProxyProtocolFilter)
		**out = **in
	}
	if in.SimpleTlsDowngrade != nil {
		in, out := &in.SimpleTlsDowngrade, &out.SimpleTlsDowngrade
		*out = new(SimpleTlsDowngrade)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionElement.
func (in *ExtensionElement) DeepCopy() *ExtensionElement {
	if in == nil {
		return nil
	}
	out := new(ExtensionElement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in FaultFilterPorts) DeepCopyInto(out *FaultFilterPorts) {
	{
		in := &in
		*out = make(FaultFilterPorts, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultFilterPorts.
func (in FaultFilterPorts) DeepCopy() FaultFilterPorts {
	if in == nil {
		return nil
	}
	out := new(FaultFilterPorts)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilteredRateLimit) DeepCopyInto(out *FilteredRateLimit) {
	*out = *in
	if in.Caller != nil {
		in, out := &in.Caller, &out.Caller
		*out = new(Service)
		(*in).DeepCopyInto(*out)
	}
	if in.HeaderMatches != nil {
		in, out := &in.HeaderMatches, &out.HeaderMatches
		*out = make([]RateLimitHeaderMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.RateLimit = in.RateLimit
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilteredRateLimit.
func (in *FilteredRateLimit) DeepCopy() *FilteredRateLimit {
	if in == nil {
		return nil
	}
	out := new(FilteredRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GRPCJsonTranscoderFilter) DeepCopyInto(out *GRPCJsonTranscoderFilter) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GRPCJsonTranscoderFilter.
func (in *GRPCJsonTranscoderFilter) DeepCopy() *GRPCJsonTranscoderFilter {
	if in == nil {
		return nil
	}
	out := new(GRPCJsonTranscoderFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayProxyFilter) DeepCopyInto(out *GatewayProxyFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayProxyFilter.
func (in *GatewayProxyFilter) DeepCopy() *GatewayProxyFilter {
	if in == nil {
		return nil
	}
	out := new(GatewayProxyFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericKey) DeepCopyInto(out *GenericKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericKey.
func (in *GenericKey) DeepCopy() *GenericKey {
	if in == nil {
		return nil
	}
	out := new(GenericKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalCanaryStrategy) DeepCopyInto(out *GlobalCanaryStrategy) {
	*out = *in
	if in.StableSubsetLabels != nil {
		in, out := &in.StableSubsetLabels, &out.StableSubsetLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CanarySubsetLabels != nil {
		in, out := &in.CanarySubsetLabels, &out.CanarySubsetLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TestSubsetLabels != nil {
		in, out := &in.TestSubsetLabels, &out.TestSubsetLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalCanaryStrategy.
func (in *GlobalCanaryStrategy) DeepCopy() *GlobalCanaryStrategy {
	if in == nil {
		return nil
	}
	out := new(GlobalCanaryStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimitConfig) DeepCopyInto(out *GlobalRateLimitConfig) {
	*out = *in
	in.BaseRateLimitConfig.DeepCopyInto(&out.BaseRateLimitConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimitConfig.
func (in *GlobalRateLimitConfig) DeepCopy() *GlobalRateLimitConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimitFilter) DeepCopyInto(out *GlobalRateLimitFilter) {
	*out = *in
	if in.RateLimitService != nil {
		in, out := &in.RateLimitService, &out.RateLimitService
		*out = new(RateLimitService)
		**out = **in
	}
	if in.RateLimitConfigs != nil {
		in, out := &in.RateLimitConfigs, &out.RateLimitConfigs
		*out = make([]GlobalRateLimitConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimitFilter.
func (in *GlobalRateLimitFilter) DeepCopy() *GlobalRateLimitFilter {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimitFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GzipContextConfig) DeepCopyInto(out *GzipContextConfig) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]Port, len(*in))
		copy(*out, *in)
	}
	if in.ContentTypes != nil {
		in, out := &in.ContentTypes, &out.ContentTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GzipContextConfig.
func (in *GzipContextConfig) DeepCopy() *GzipContextConfig {
	if in == nil {
		return nil
	}
	out := new(GzipContextConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GzipFilter) DeepCopyInto(out *GzipFilter) {
	*out = *in
	if in.InboundConfig != nil {
		in, out := &in.InboundConfig, &out.InboundConfig
		*out = new(GzipContextConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OutboundConfig != nil {
		in, out := &in.OutboundConfig, &out.OutboundConfig
		*out = new(GzipContextConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GzipFilter.
func (in *GzipFilter) DeepCopy() *GzipFilter {
	if in == nil {
		return nil
	}
	out := new(GzipFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPHealthCheck) DeepCopyInto(out *HTTPHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPHealthCheck.
func (in *HTTPHealthCheck) DeepCopy() *HTTPHealthCheck {
	if in == nil {
		return nil
	}
	out := new(HTTPHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Header) DeepCopyInto(out *Header) {
	*out = *in
	if in.SafeRegexMatch != nil {
		in, out := &in.SafeRegexMatch, &out.SafeRegexMatch
		*out = new(SafeRegexMatch)
		**out = **in
	}
	if in.RangeMatch != nil {
		in, out := &in.RangeMatch, &out.RangeMatch
		*out = new(RangeMatch)
		**out = **in
	}
	if in.StringMatch != nil {
		in, out := &in.StringMatch, &out.StringMatch
		*out = new(StringMatch)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Header.
func (in *Header) DeepCopy() *Header {
	if in == nil {
		return nil
	}
	out := new(Header)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderMutation) DeepCopyInto(out *HeaderMutation) {
	*out = *in
	if in.AppendOrAdd != nil {
		in, out := &in.AppendOrAdd, &out.AppendOrAdd
		*out = new(HeaderValue)
		**out = **in
	}
	if in.AppendIfAbsent != nil {
		in, out := &in.AppendIfAbsent, &out.AppendIfAbsent
		*out = new(HeaderValue)
		**out = **in
	}
	if in.ReplaceOrAdd != nil {
		in, out := &in.ReplaceOrAdd, &out.ReplaceOrAdd
		*out = new(HeaderValue)
		**out = **in
	}
	if in.ReplaceIfExists != nil {
		in, out := &in.ReplaceIfExists, &out.ReplaceIfExists
		*out = new(HeaderValue)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderMutation.
func (in *HeaderMutation) DeepCopy() *HeaderMutation {
	if in == nil {
		return nil
	}
	out := new(HeaderMutation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderValue) DeepCopyInto(out *HeaderValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderValue.
func (in *HeaderValue) DeepCopy() *HeaderValue {
	if in == nil {
		return nil
	}
	out := new(HeaderValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderValueMatch) DeepCopyInto(out *HeaderValueMatch) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]Header, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderValueMatch.
func (in *HeaderValueMatch) DeepCopy() *HeaderValueMatch {
	if in == nil {
		return nil
	}
	out := new(HeaderValueMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckFilter) DeepCopyInto(out *HealthCheckFilter) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = make([]PortAndPath, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckFilter.
func (in *HealthCheckFilter) DeepCopy() *HealthCheckFilter {
	if in == nil {
		return nil
	}
	out := new(HealthCheckFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckerConfig) DeepCopyInto(out *HealthCheckerConfig) {
	*out = *in
	if in.HTTPHealthCheck != nil {
		in, out := &in.HTTPHealthCheck, &out.HTTPHealthCheck
		*out = new(HTTPHealthCheck)
		**out = **in
	}
	if in.RedisHealthCheck != nil {
		in, out := &in.RedisHealthCheck, &out.RedisHealthCheck
		*out = new(RedisHealthCheck)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckerConfig.
func (in *HealthCheckerConfig) DeepCopy() *HealthCheckerConfig {
	if in == nil {
		return nil
	}
	out := new(HealthCheckerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Host) DeepCopyInto(out *Host) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Host.
func (in *Host) DeepCopy() *Host {
	if in == nil {
		return nil
	}
	out := new(Host)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpFaultFilter) DeepCopyInto(out *HttpFaultFilter) {
	*out = *in
	if in.Abort != nil {
		in, out := &in.Abort, &out.Abort
		*out = new(HttpFaultFilterAbort)
		(*in).DeepCopyInto(*out)
	}
	if in.RedisAbort != nil {
		in, out := &in.RedisAbort, &out.RedisAbort
		*out = new(RedisFaultFilterAbort)
		(*in).DeepCopyInto(*out)
	}
	if in.Delay != nil {
		in, out := &in.Delay, &out.Delay
		*out = new(HttpFaultFilterDelay)
		(*in).DeepCopyInto(*out)
	}
	if in.RedisDelay != nil {
		in, out := &in.RedisDelay, &out.RedisDelay
		*out = new(RedisFaultFilterDelay)
		(*in).DeepCopyInto(*out)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make(FaultFilterPorts, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpFaultFilter.
func (in *HttpFaultFilter) DeepCopy() *HttpFaultFilter {
	if in == nil {
		return nil
	}
	out := new(HttpFaultFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpFaultFilterAbort) DeepCopyInto(out *HttpFaultFilterAbort) {
	*out = *in
	if in.Percentage != nil {
		in, out := &in.Percentage, &out.Percentage
		*out = new(Percentage)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpFaultFilterAbort.
func (in *HttpFaultFilterAbort) DeepCopy() *HttpFaultFilterAbort {
	if in == nil {
		return nil
	}
	out := new(HttpFaultFilterAbort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpFaultFilterDelay) DeepCopyInto(out *HttpFaultFilterDelay) {
	*out = *in
	if in.Percentage != nil {
		in, out := &in.Percentage, &out.Percentage
		*out = new(Percentage)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpFaultFilterDelay.
func (in *HttpFaultFilterDelay) DeepCopy() *HttpFaultFilterDelay {
	if in == nil {
		return nil
	}
	out := new(HttpFaultFilterDelay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InboundStats) DeepCopyInto(out *InboundStats) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InboundStats.
func (in *InboundStats) DeepCopy() *InboundStats {
	if in == nil {
		return nil
	}
	out := new(InboundStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressCookieAttribute) DeepCopyInto(out *IngressCookieAttribute) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.Cookies != nil {
		in, out := &in.Cookies, &out.Cookies
		*out = make([]Cookie, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressCookieAttribute.
func (in *IngressCookieAttribute) DeepCopy() *IngressCookieAttribute {
	if in == nil {
		return nil
	}
	out := new(IngressCookieAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressLua) DeepCopyInto(out *IngressLua) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]IgPort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressLua.
func (in *IngressLua) DeepCopy() *IngressLua {
	if in == nil {
		return nil
	}
	out := new(IngressLua)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressRateLimitConfig) DeepCopyInto(out *IngressRateLimitConfig) {
	*out = *in
	in.BaseRateLimitConfig.DeepCopyInto(&out.BaseRateLimitConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressRateLimitConfig.
func (in *IngressRateLimitConfig) DeepCopy() *IngressRateLimitConfig {
	if in == nil {
		return nil
	}
	out := new(IngressRateLimitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressRateLimitFilter) DeepCopyInto(out *IngressRateLimitFilter) {
	*out = *in
	if in.RateLimitService != nil {
		in, out := &in.RateLimitService, &out.RateLimitService
		*out = new(RateLimitService)
		**out = **in
	}
	if in.RateLimitConfigs != nil {
		in, out := &in.RateLimitConfigs, &out.RateLimitConfigs
		*out = make([]IngressRateLimitConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressRateLimitFilter.
func (in *IngressRateLimitFilter) DeepCopy() *IngressRateLimitFilter {
	if in == nil {
		return nil
	}
	out := new(IngressRateLimitFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressRequestHeaders) DeepCopyInto(out *IngressRequestHeaders) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]IgPort, len(*in))
		copy(*out, *in)
	}
	if in.Mutations != nil {
		in, out := &in.Mutations, &out.Mutations
		*out = make([]HeaderMutation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressRequestHeaders.
func (in *IngressRequestHeaders) DeepCopy() *IngressRequestHeaders {
	if in == nil {
		return nil
	}
	out := new(IngressRequestHeaders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressResponseHeaders) DeepCopyInto(out *IngressResponseHeaders) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]IgPort, len(*in))
		copy(*out, *in)
	}
	if in.Mutations != nil {
		in, out := &in.Mutations, &out.Mutations
		*out = make([]HeaderMutation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressResponseHeaders.
func (in *IngressResponseHeaders) DeepCopy() *IngressResponseHeaders {
	if in == nil {
		return nil
	}
	out := new(IngressResponseHeaders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyValuePair) DeepCopyInto(out *KeyValuePair) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyValuePair.
func (in *KeyValuePair) DeepCopy() *KeyValuePair {
	if in == nil {
		return nil
	}
	out := new(KeyValuePair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerConfig) DeepCopyInto(out *LoadBalancerConfig) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.OverrideHostStatus != nil {
		in, out := &in.OverrideHostStatus, &out.OverrideHostStatus
		*out = new(OverrideHostStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerConfig.
func (in *LoadBalancerConfig) DeepCopy() *LoadBalancerConfig {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalRateLimitFilter) DeepCopyInto(out *LocalRateLimitFilter) {
	*out = *in
	if in.PortRateLimits != nil {
		in, out := &in.PortRateLimits, &out.PortRateLimits
		*out = make([]PortRateLimit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalRateLimitFilter.
func (in *LocalRateLimitFilter) DeepCopy() *LocalRateLimitFilter {
	if in == nil {
		return nil
	}
	out := new(LocalRateLimitFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaxOutboundFrames) DeepCopyInto(out *MaxOutboundFrames) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaxOutboundFrames.
func (in *MaxOutboundFrames) DeepCopy() *MaxOutboundFrames {
	if in == nil {
		return nil
	}
	out := new(MaxOutboundFrames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshOperator) DeepCopyInto(out *MeshOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshOperator.
func (in *MeshOperator) DeepCopy() *MeshOperator {
	if in == nil {
		return nil
	}
	out := new(MeshOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeshOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshOperatorList) DeepCopyInto(out *MeshOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MeshOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshOperatorList.
func (in *MeshOperatorList) DeepCopy() *MeshOperatorList {
	if in == nil {
		return nil
	}
	out := new(MeshOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeshOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshOperatorSpec) DeepCopyInto(out *MeshOperatorSpec) {
	*out = *in
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make([]ExtensionElement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceSelector != nil {
		in, out := &in.ServiceSelector, &out.ServiceSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Overlays != nil {
		in, out := &in.Overlays, &out.Overlays
		*out = make([]Overlay, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshOperatorSpec.
func (in *MeshOperatorSpec) DeepCopy() *MeshOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(MeshOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshOperatorStatus) DeepCopyInto(out *MeshOperatorStatus) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make(map[string]*ServiceStatus, len(*in))
		for key, val := range *in {
			var outVal *ServiceStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(ServiceStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.ServiceEntries != nil {
		in, out := &in.ServiceEntries, &out.ServiceEntries
		*out = make(map[string]*ServiceStatus, len(*in))
		for key, val := range *in {
			var outVal *ServiceStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(ServiceStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.RelatedResources != nil {
		in, out := &in.RelatedResources, &out.RelatedResources
		*out = make([]*ResourceStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ResourceStatus)
				**out = **in
			}
		}
	}
	if in.LastReconciledTime != nil {
		in, out := &in.LastReconciledTime, &out.LastReconciledTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshOperatorStatus.
func (in *MeshOperatorStatus) DeepCopy() *MeshOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(MeshOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshRequestHeaders) DeepCopyInto(out *MeshRequestHeaders) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.Mutations != nil {
		in, out := &in.Mutations, &out.Mutations
		*out = make([]HeaderMutation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshRequestHeaders.
func (in *MeshRequestHeaders) DeepCopy() *MeshRequestHeaders {
	if in == nil {
		return nil
	}
	out := new(MeshRequestHeaders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshRequestHeadersPerRoute) DeepCopyInto(out *MeshRequestHeadersPerRoute) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]Route, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshRequestHeadersPerRoute.
func (in *MeshRequestHeadersPerRoute) DeepCopy() *MeshRequestHeadersPerRoute {
	if in == nil {
		return nil
	}
	out := new(MeshRequestHeadersPerRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshServiceMetadata) DeepCopyInto(out *MeshServiceMetadata) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshServiceMetadata.
func (in *MeshServiceMetadata) DeepCopy() *MeshServiceMetadata {
	if in == nil {
		return nil
	}
	out := new(MeshServiceMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeshServiceMetadata) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshServiceMetadataList) DeepCopyInto(out *MeshServiceMetadataList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MeshServiceMetadata, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshServiceMetadataList.
func (in *MeshServiceMetadataList) DeepCopy() *MeshServiceMetadataList {
	if in == nil {
		return nil
	}
	out := new(MeshServiceMetadataList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeshServiceMetadataList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshServiceMetadataSpec) DeepCopyInto(out *MeshServiceMetadataSpec) {
	*out = *in
	if in.OwnedResources != nil {
		in, out := &in.OwnedResources, &out.OwnedResources
		*out = make([]OwnedResource, len(*in))
		copy(*out, *in)
	}
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = make([]Owner, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshServiceMetadataSpec.
func (in *MeshServiceMetadataSpec) DeepCopy() *MeshServiceMetadataSpec {
	if in == nil {
		return nil
	}
	out := new(MeshServiceMetadataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshServiceMetadataStatus) DeepCopyInto(out *MeshServiceMetadataStatus) {
	*out = *in
	if in.ReconciledObjectHash != nil {
		in, out := &in.ReconciledObjectHash, &out.ReconciledObjectHash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastReconciledTime != nil {
		in, out := &in.LastReconciledTime, &out.LastReconciledTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshServiceMetadataStatus.
func (in *MeshServiceMetadataStatus) DeepCopy() *MeshServiceMetadataStatus {
	if in == nil {
		return nil
	}
	out := new(MeshServiceMetadataStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixedMode) DeepCopyInto(out *MixedMode) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]TargetedPort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixedMode.
func (in *MixedMode) DeepCopy() *MixedMode {
	if in == nil {
		return nil
	}
	out := new(MixedMode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2AuthorizatonRule) DeepCopyInto(out *OAuth2AuthorizatonRule) {
	*out = *in
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]HttpMethod, len(*in))
		copy(*out, *in)
	}
	if in.EmployeeTypes != nil {
		in, out := &in.EmployeeTypes, &out.EmployeeTypes
		*out = make([]EmployeeType, len(*in))
		copy(*out, *in)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WorkloadOwnerAccess != nil {
		in, out := &in.WorkloadOwnerAccess, &out.WorkloadOwnerAccess
		*out = new(WorkloadOwnerAccessType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2AuthorizatonRule.
func (in *OAuth2AuthorizatonRule) DeepCopy() *OAuth2AuthorizatonRule {
	if in == nil {
		return nil
	}
	out := new(OAuth2AuthorizatonRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2Filter) DeepCopyInto(out *OAuth2Filter) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.AuthScopes != nil {
		in, out := &in.AuthScopes, &out.AuthScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthorizationRules != nil {
		in, out := &in.AuthorizationRules, &out.AuthorizationRules
		*out = make([]OAuth2AuthorizatonRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]Oauth2Provider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.OauthClient = in.OauthClient
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2Filter.
func (in *OAuth2Filter) DeepCopy() *OAuth2Filter {
	if in == nil {
		return nil
	}
	out := new(OAuth2Filter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Oauth2Provider) DeepCopyInto(out *Oauth2Provider) {
	*out = *in
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Oauth2Provider.
func (in *Oauth2Provider) DeepCopy() *Oauth2Provider {
	if in == nil {
		return nil
	}
	out := new(Oauth2Provider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OauthClient) DeepCopyInto(out *OauthClient) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OauthClient.
func (in *OauthClient) DeepCopy() *OauthClient {
	if in == nil {
		return nil
	}
	out := new(OauthClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutboundStats) DeepCopyInto(out *OutboundStats) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutboundStats.
func (in *OutboundStats) DeepCopy() *OutboundStats {
	if in == nil {
		return nil
	}
	out := new(OutboundStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Overlay) DeepCopyInto(out *Overlay) {
	*out = *in
	in.StrategicMergePatch.DeepCopyInto(&out.StrategicMergePatch)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Overlay.
func (in *Overlay) DeepCopy() *Overlay {
	if in == nil {
		return nil
	}
	out := new(Overlay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverrideHostStatus) DeepCopyInto(out *OverrideHostStatus) {
	*out = *in
	if in.Statuses != nil {
		in, out := &in.Statuses, &out.Statuses
		*out = make([]HostStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverrideHostStatus.
func (in *OverrideHostStatus) DeepCopy() *OverrideHostStatus {
	if in == nil {
		return nil
	}
	out := new(OverrideHostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnedResource) DeepCopyInto(out *OwnedResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnedResource.
func (in *OwnedResource) DeepCopy() *OwnedResource {
	if in == nil {
		return nil
	}
	out := new(OwnedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Owner) DeepCopyInto(out *Owner) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Owner.
func (in *Owner) DeepCopy() *Owner {
	if in == nil {
		return nil
	}
	out := new(Owner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Percentage) DeepCopyInto(out *Percentage) {
	*out = *in
	if in.Numerator != nil {
		in, out := &in.Numerator, &out.Numerator
		*out = new(int)
		**out = **in
	}
	if in.Denominator != nil {
		in, out := &in.Denominator, &out.Denominator
		*out = new(PercentageDenominator)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Percentage.
func (in *Percentage) DeepCopy() *Percentage {
	if in == nil {
		return nil
	}
	out := new(Percentage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortAndPath) DeepCopyInto(out *PortAndPath) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortAndPath.
func (in *PortAndPath) DeepCopy() *PortAndPath {
	if in == nil {
		return nil
	}
	out := new(PortAndPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortConfig) DeepCopyInto(out *PortConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortConfig.
func (in *PortConfig) DeepCopy() *PortConfig {
	if in == nil {
		return nil
	}
	out := new(PortConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortLevelHealthCheck) DeepCopyInto(out *PortLevelHealthCheck) {
	*out = *in
	if in.HealthCheckerConfig != nil {
		in, out := &in.HealthCheckerConfig, &out.HealthCheckerConfig
		*out = new(HealthCheckerConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortLevelHealthCheck.
func (in *PortLevelHealthCheck) DeepCopy() *PortLevelHealthCheck {
	if in == nil {
		return nil
	}
	out := new(PortLevelHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortRateLimit) DeepCopyInto(out *PortRateLimit) {
	*out = *in
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(RateLimit)
		**out = **in
	}
	if in.FilteredRateLimits != nil {
		in, out := &in.FilteredRateLimits, &out.FilteredRateLimits
		*out = make([]FilteredRateLimit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortRateLimit.
func (in *PortRateLimit) DeepCopy() *PortRateLimit {
	if in == nil {
		return nil
	}
	out := new(PortRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyProtocolFilter) DeepCopyInto(out *ProxyProtocolFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyProtocolFilter.
func (in *ProxyProtocolFilter) DeepCopy() *ProxyProtocolFilter {
	if in == nil {
		return nil
	}
	out := new(ProxyProtocolFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RangeMatch) DeepCopyInto(out *RangeMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RangeMatch.
func (in *RangeMatch) DeepCopy() *RangeMatch {
	if in == nil {
		return nil
	}
	out := new(RangeMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimit) DeepCopyInto(out *RateLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimit.
func (in *RateLimit) DeepCopy() *RateLimit {
	if in == nil {
		return nil
	}
	out := new(RateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitHeaderMatch) DeepCopyInto(out *RateLimitHeaderMatch) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitHeaderMatch.
func (in *RateLimitHeaderMatch) DeepCopy() *RateLimitHeaderMatch {
	if in == nil {
		return nil
	}
	out := new(RateLimitHeaderMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitService) DeepCopyInto(out *RateLimitService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitService.
func (in *RateLimitService) DeepCopy() *RateLimitService {
	if in == nil {
		return nil
	}
	out := new(RateLimitService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisFaultFilterAbort) DeepCopyInto(out *RedisFaultFilterAbort) {
	*out = *in
	if in.Percentage != nil {
		in, out := &in.Percentage, &out.Percentage
		*out = new(Percentage)
		(*in).DeepCopyInto(*out)
	}
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisFaultFilterAbort.
func (in *RedisFaultFilterAbort) DeepCopy() *RedisFaultFilterAbort {
	if in == nil {
		return nil
	}
	out := new(RedisFaultFilterAbort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisFaultFilterDelay) DeepCopyInto(out *RedisFaultFilterDelay) {
	*out = *in
	if in.Percentage != nil {
		in, out := &in.Percentage, &out.Percentage
		*out = new(Percentage)
		(*in).DeepCopyInto(*out)
	}
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisFaultFilterDelay.
func (in *RedisFaultFilterDelay) DeepCopy() *RedisFaultFilterDelay {
	if in == nil {
		return nil
	}
	out := new(RedisFaultFilterDelay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisHealthCheck) DeepCopyInto(out *RedisHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisHealthCheck.
func (in *RedisHealthCheck) DeepCopy() *RedisHealthCheck {
	if in == nil {
		return nil
	}
	out := new(RedisHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestHeaders) DeepCopyInto(out *RequestHeaders) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestHeaders.
func (in *RequestHeaders) DeepCopy() *RequestHeaders {
	if in == nil {
		return nil
	}
	out := new(RequestHeaders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceStatus) DeepCopyInto(out *ResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceStatus.
func (in *ResourceStatus) DeepCopy() *ResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Route) DeepCopyInto(out *Route) {
	*out = *in
	if in.PathMatches != nil {
		in, out := &in.PathMatches, &out.PathMatches
		*out = make([]StringMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Mutations != nil {
		in, out := &in.Mutations, &out.Mutations
		*out = make([]HeaderMutation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Route.
func (in *Route) DeepCopy() *Route {
	if in == nil {
		return nil
	}
	out := new(Route)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafeRegexMatch) DeepCopyInto(out *SafeRegexMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafeRegexMatch.
func (in *SafeRegexMatch) DeepCopy() *SafeRegexMatch {
	if in == nil {
		return nil
	}
	out := new(SafeRegexMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerMaxOutboundFrames) DeepCopyInto(out *ServerMaxOutboundFrames) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerMaxOutboundFrames.
func (in *ServerMaxOutboundFrames) DeepCopy() *ServerMaxOutboundFrames {
	if in == nil {
		return nil
	}
	out := new(ServerMaxOutboundFrames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
	if in.SpiffeElements != nil {
		in, out := &in.SpiffeElements, &out.SpiffeElements
		*out = make([]KeyValuePair, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSelector) DeepCopyInto(out *ServiceSelector) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSelector.
func (in *ServiceSelector) DeepCopy() *ServiceSelector {
	if in == nil {
		return nil
	}
	out := new(ServiceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
	if in.RelatedResources != nil {
		in, out := &in.RelatedResources, &out.RelatedResources
		*out = make([]*ResourceStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ResourceStatus)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarConfig) DeepCopyInto(out *SidecarConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarConfig.
func (in *SidecarConfig) DeepCopy() *SidecarConfig {
	if in == nil {
		return nil
	}
	out := new(SidecarConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SidecarConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarConfigList) DeepCopyInto(out *SidecarConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SidecarConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarConfigList.
func (in *SidecarConfigList) DeepCopy() *SidecarConfigList {
	if in == nil {
		return nil
	}
	out := new(SidecarConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SidecarConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarConfigSpec) DeepCopyInto(out *SidecarConfigSpec) {
	*out = *in
	if in.WorkloadSelector != nil {
		in, out := &in.WorkloadSelector, &out.WorkloadSelector
		*out = new(WorkloadSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.EgressHosts != nil {
		in, out := &in.EgressHosts, &out.EgressHosts
		*out = new(EgressHosts)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarConfigSpec.
func (in *SidecarConfigSpec) DeepCopy() *SidecarConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SidecarConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarConfigStatus) DeepCopyInto(out *SidecarConfigStatus) {
	*out = *in
	if in.LastReconciledTime != nil {
		in, out := &in.LastReconciledTime, &out.LastReconciledTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarConfigStatus.
func (in *SidecarConfigStatus) DeepCopy() *SidecarConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SidecarConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleTlsDowngrade) DeepCopyInto(out *SimpleTlsDowngrade) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleTlsDowngrade.
func (in *SimpleTlsDowngrade) DeepCopy() *SimpleTlsDowngrade {
	if in == nil {
		return nil
	}
	out := new(SimpleTlsDowngrade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SparkConfiguration) DeepCopyInto(out *SparkConfiguration) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]PortConfig, len(*in))
		copy(*out, *in)
	}
	if in.EgressHosts != nil {
		in, out := &in.EgressHosts, &out.EgressHosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SelectorLabels != nil {
		in, out := &in.SelectorLabels, &out.SelectorLabels
		*out = make([]KeyValuePair, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SparkConfiguration.
func (in *SparkConfiguration) DeepCopy() *SparkConfiguration {
	if in == nil {
		return nil
	}
	out := new(SparkConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatsFilter) DeepCopyInto(out *StatsFilter) {
	*out = *in
	if in.Outbound != nil {
		in, out := &in.Outbound, &out.Outbound
		*out = new(OutboundStats)
		**out = **in
	}
	if in.Inbound != nil {
		in, out := &in.Inbound, &out.Inbound
		*out = new(InboundStats)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatsFilter.
func (in *StatsFilter) DeepCopy() *StatsFilter {
	if in == nil {
		return nil
	}
	out := new(StatsFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringMatch) DeepCopyInto(out *StringMatch) {
	*out = *in
	if in.SafeRegex != nil {
		in, out := &in.SafeRegex, &out.SafeRegex
		*out = new(SafeRegexMatch)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringMatch.
func (in *StringMatch) DeepCopy() *StringMatch {
	if in == nil {
		return nil
	}
	out := new(StringMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSPHashPolicy) DeepCopyInto(out *TSPHashPolicy) {
	*out = *in
	if in.XFCCConfig != nil {
		in, out := &in.XFCCConfig, &out.XFCCConfig
		*out = new(TSPXFCCHashConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSPHashPolicy.
func (in *TSPHashPolicy) DeepCopy() *TSPHashPolicy {
	if in == nil {
		return nil
	}
	out := new(TSPHashPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSPRoute) DeepCopyInto(out *TSPRoute) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
	in.Destination.DeepCopyInto(&out.Destination)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSPRoute.
func (in *TSPRoute) DeepCopy() *TSPRoute {
	if in == nil {
		return nil
	}
	out := new(TSPRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSPRouteDestination) DeepCopyInto(out *TSPRouteDestination) {
	*out = *in
	if in.HashPolicy != nil {
		in, out := &in.HashPolicy, &out.HashPolicy
		*out = new(TSPHashPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.ShuffleShardingPolicy != nil {
		in, out := &in.ShuffleShardingPolicy, &out.ShuffleShardingPolicy
		*out = new(TSPShuffleShardPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSPRouteDestination.
func (in *TSPRouteDestination) DeepCopy() *TSPRouteDestination {
	if in == nil {
		return nil
	}
	out := new(TSPRouteDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSPRouteMatch) DeepCopyInto(out *TSPRouteMatch) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]TSPStringMatch, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSPRouteMatch.
func (in *TSPRouteMatch) DeepCopy() *TSPRouteMatch {
	if in == nil {
		return nil
	}
	out := new(TSPRouteMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSPShuffleShardPolicy) DeepCopyInto(out *TSPShuffleShardPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSPShuffleShardPolicy.
func (in *TSPShuffleShardPolicy) DeepCopy() *TSPShuffleShardPolicy {
	if in == nil {
		return nil
	}
	out := new(TSPShuffleShardPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSPStringMatch) DeepCopyInto(out *TSPStringMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSPStringMatch.
func (in *TSPStringMatch) DeepCopy() *TSPStringMatch {
	if in == nil {
		return nil
	}
	out := new(TSPStringMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSPXFCCHashConfig) DeepCopyInto(out *TSPXFCCHashConfig) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]TSPXFCCKey, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSPXFCCHashConfig.
func (in *TSPXFCCHashConfig) DeepCopy() *TSPXFCCHashConfig {
	if in == nil {
		return nil
	}
	out := new(TSPXFCCHashConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetedPort) DeepCopyInto(out *TargetedPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetedPort.
func (in *TargetedPort) DeepCopy() *TargetedPort {
	if in == nil {
		return nil
	}
	out := new(TargetedPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryConfig) DeepCopyInto(out *TelemetryConfig) {
	*out = *in
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = new(TracingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AccessLog != nil {
		in, out := &in.AccessLog, &out.AccessLog
		*out = new(AccessLogConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryConfig.
func (in *TelemetryConfig) DeepCopy() *TelemetryConfig {
	if in == nil {
		return nil
	}
	out := new(TelemetryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingConfig) DeepCopyInto(out *TracingConfig) {
	*out = *in
	if in.SamplingPercentage != nil {
		in, out := &in.SamplingPercentage, &out.SamplingPercentage
		*out = new(Percentage)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadMode != nil {
		in, out := &in.WorkloadMode, &out.WorkloadMode
		*out = new(WorkloadMode)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingConfig.
func (in *TracingConfig) DeepCopy() *TracingConfig {
	if in == nil {
		return nil
	}
	out := new(TracingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficShardingPolicy) DeepCopyInto(out *TrafficShardingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficShardingPolicy.
func (in *TrafficShardingPolicy) DeepCopy() *TrafficShardingPolicy {
	if in == nil {
		return nil
	}
	out := new(TrafficShardingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficShardingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficShardingPolicyList) DeepCopyInto(out *TrafficShardingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrafficShardingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficShardingPolicyList.
func (in *TrafficShardingPolicyList) DeepCopy() *TrafficShardingPolicyList {
	if in == nil {
		return nil
	}
	out := new(TrafficShardingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficShardingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficShardingPolicySpec) DeepCopyInto(out *TrafficShardingPolicySpec) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]TSPRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ServiceSelector.DeepCopyInto(&out.ServiceSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficShardingPolicySpec.
func (in *TrafficShardingPolicySpec) DeepCopy() *TrafficShardingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(TrafficShardingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficShardingPolicyStatus) DeepCopyInto(out *TrafficShardingPolicyStatus) {
	*out = *in
	if in.MatchedServices != nil {
		in, out := &in.MatchedServices, &out.MatchedServices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficShardingPolicyStatus.
func (in *TrafficShardingPolicyStatus) DeepCopy() *TrafficShardingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(TrafficShardingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSelector) DeepCopyInto(out *WorkloadSelector) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSelector.
func (in *WorkloadSelector) DeepCopy() *WorkloadSelector {
	if in == nil {
		return nil
	}
	out := new(WorkloadSelector)
	in.DeepCopyInto(out)
	return out
}
